### ISSUE TITLE
Few-Shot Relation Extraction

### ISSUE THREAD

**Issue by fillipefbr** [fractalego/fewrel_zero_shot#2]
Hi! Thank you so much for this work. 

I have a question: is it possible to extract relations in a Few-Shot approach? 
For example, instead of giving only the surface forms of the desired relations, I would also give 1 or 5 examples for each relation. 
If you could give me some examples about how to do it or include this functionality in the code I would really appreciate it.

Thank you!

**Comment by fractalego** [comment]
Hi FIllipe,
What a great question! I believe you can use directly the examples you have in place of the surface form. The relation you extract is then the one associated with the best score.

This can be a bit slow, because you'll have to go through all of the relations sequentially. One way to speed it up would be to use batch processing in prediction, which would require some changes to the code. Another way to make the system faster is to pre-select the examples by some similarity measure with your sentence (like the Retriever trick for Question Answering)

This being said, I don't know the F1 score for few shot extraction. After all, the system has been trained for zero-shot. I do however expect the F1 score to go up with the number of examples. I just don't know by how much.

If you want to use a "proper" few shot model, I suggest you have a look at Google's "Matching the Blanks" paper. 

Hope this helps!

**Comment by fillipefbr** [comment]
Thank you, Alberto!

I will try to directly use the examples and follow your suggestions. I'm new to Zero-Shot and Few-Shot learning for Relation Extraction, I'm trying to research new ways to deal with low samples for practical applications in a personal project I'm working on. I really appreciate your work and your help!

**Comment by fractalego** [comment]
My pleasure! Happy to help. 
You have probably already seen it: This specific project has been uploaded to Huggingface for a quicker installation.
https://huggingface.co/fractalego/fewrel-zero-shot
